### ISSUE TITLE
reduce logging to keep console clean

### ISSUE THREAD

**Issue by nkleemann** [miunau/hexwave_msp#1]
Hey, first of all thank you for bringing hexwave over to Max!

The only thing that keeps me from using it is that it floods my Max console with thousands of messages after modulating peak time at signal rate. I've traced the message down to line 125 of `hexwave~.c`: `post("float: %f, in: %i", f, in);`

Can you remove this `post` call, and others alike (every non-initialization call)?

**Comment by miunau** [comment]
Oops!!!! I forgot to update the version on here without them. Will do now, thanks for notifying!
